
quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: '${URL_POSTGRES:jdbc:postgresql://localhost:5432/teste}'

  flyway:
    migrate-at-start: true

  http:
    cors:
      ~: true
      methods: GET, PUT, POST, DELETE, OPTIONS
      headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
      origins: /.*/

