quarkus:
  datasource:
    db-kind: postgresql
    username: '${USERNAME_POSTGRES:postgres}'
    password: '${PASSWORD_POSTGRES:postgres}'
    jdbc:
      url: '${URL_POSTGRES:jdbc:postgresql://localhost:5432/pontoeventos}'

  flyway:
    migrate-at-start: true

  http:
    cors:
      ~: true
      methods: GET, PUT, POST, DELETE, OPTIONS
      headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
      origins: /.*/

